title: Lifestack
email: ashon8813@gmail.com
description: >-
  Thoughts and Experiences
  for Software Development
baseurl: ""
url: "https://ashon.github.io"
lang: ko_KR

google_analytics: UA-151348212-1

theme: minima
markdown: kramdown
minima:
  social_links:
    github: ashon
    linkedin: ju-won-lee-9662108a
    rss: subscribe

plugins:
- jekyll-seo-tag
- jekyll-feed
- jekyll-archives
- jekyll-sitemap
- jekyll-last-modified-at

jekyll-archives:
  enabled: []
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
